---
fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '9.7.0'
    apt:
      repo: 'puppetlabs/apt'
      ref: '9.4.0'
    yumrepo:
      repo: 'puppetlabs/yumrepo_core'
      ref: '3.0.1'
