---
require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: "2.7"
  Include:
    - "**/*.rb"
  Exclude:
    - bin/*
    - ".vendor/**/*"
    - "**/Gemfile"
    - "**/Rakefile"
    - pkg/**/*
    - spec/fixtures/**/*
    - vendor/**/*

Layout/LineLength:
  Description: People have wide screens, use them.
  Max: 200

RSpec/BeforeAfterAll:
  Description: Beware of using after(:all) as it may cause state to leak between tests. A necessary evil in acceptance testing.
  Exclude:
    - spec/acceptance/**/*.rb

RSpec/HookArgument:
  Description: Prefer explicit :each argument, matching existing module's style
  EnforcedStyle: each

RSpec/DescribeClass:
  Description: Functions are not classes.
  Exclude:
    - spec/acceptance/**/*.rb

Style/BlockDelimiters:
  Description: Prefer braces for chaining. Mostly an ideological thing, but it's good to be consistent.
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Description: Compact style reduces the indentation of embedded classes and modules.
  EnforcedStyle: compact

Style/EmptyElse:
  Description: Enforce against empty else clauses, but allow `nil` for clarity.
  EnforcedStyle: empty

Style/FormatString:
  Description: Following the main puppet project's style, prefer the percent format.
  EnforcedStyle: percent

Style/FormatStringToken:
  Description: Following the main puppet project's style, prefer the annotated format.
  EnforcedStyle: annotated

Style/Lambda:
  Description: Prefer the lambda method over the literal lambda syntax.
  EnforcedStyle: literal

Style/RegexpLiteral:
  Description: Community preference, mostly a matter of taste.
  EnforcedStyle: slashes

Style/TernaryParentheses:
  Description: Prefer parentheses for multi-term ternary conditions.
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInHashLiteral:
  Description: Prefer always trailing comma in hash literals for easier diff.
  EnforcedStyleForMultiline: comma

Style/SymbolArray:
  Description: Use percent literal syntax consistently.
  EnforcedStyle: percent

Style/WordArray:
  Description: Use percent literal syntax consistently.
  EnforcedStyle: percent

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
