---
# PDK sync configuration
# This file configures how PDK updates module files

.gitignore:
  paths:
    - /coverage/
    - /log/
    - /pkg/
    - /spec/fixtures/modules/
    - /vendor/
    - /.vendor/
    - /.bundle/
    - /Gemfile.lock
    - /.idea/
    - /.vscode/

.gitlab-ci.yml:
  delete: true

.travis.yml:
  delete: true

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'pdk'

spec/spec_helper.rb:
  mock_with: ':rspec'
