---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.26"
		- PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.0.0"
    - PUPPET_GEM_VERSION="~> 4.1.0"
    - PUPPET_GEM_VERSION="~> 4.2.0"
    - PUPPET_GEM_VERSION="~> 4.3.0"
    - PUPPET_GEM_VERSION="~> 4.4.0"
    - PUPPET_GEM_VERSION="~> 4"
    - PUPPET_GEM_VERSION="~> 4" STRICT_VARIABLES="yes"

sudo: false

script: "bundle exec rake validate && bundle exec rake lint"

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.4.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.1.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.2.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.3.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.4.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.5.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.6.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.7.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3.8.0"
		- rvm: 2.2.0
		- env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.1.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.2.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.3.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.4.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.5.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.6.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.7.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3.8.0"
		- rvm: 2.3.0
		- env: PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"

notifications:
  email: false

deploy:
	provider: puppetforge
	user: CERNOps
	password:
		secure: "XJpaIghLTjeXOmB6JIRYvKjL2GfVNAYm7Cs0KnTYiuzBieTpTmaJ7p6U/H0qLzhWrzlflu+mI7Y/UAjUxOarUbmwtid5f+vwJClJtPGTxxU4IPFLb3GRjPmSFaof+w4yOtG0aTOziK6MWpxWyWfb1mmU5NuXGXQIsesW20iB70v6ciSWKt6qXjdTpXL0GkDxp0fDwndLZZDPn4v3Bg4HMk6k9yVGfCFsT+ACYEvdHimLTwYXfBlaXDfmx2lp/sngUibXz2dQvKrZ7B4VaRp3/W2ku/X7ar5wXbsAiUkF93BL7kazD68FNNhj6EJB9wWH1RoiCaNC57w94GpRuDov0DjIPOkEatq5AK1+skVsy0ROofjhBWyz1m2R9ywLtQ/MNPQGIaiLv3m75/oTlullBrBsadiQNbH1tLP0QgSuuDDobmWtcfEJq2QJvw0fuZGacPEu1vbY8w/2h+H4iEfIE8uS50wHPb6mH43UgNbGpcfmQPhzbSM8oyAT01HmRnjPm3L0IFpEpDBujhMe7RfCeq8qVIsnsd3+RjrWEA7caYNHOdqzsuP1zT0w9bPUyG7Vuzfk/EPDXowTodt9fBJYU7s6bBxGP/J26JagKBGAY9w0U9L4/sogvW+oLAAPCKvGdufJhScjSpX9NsjNJTwRKJBnQ8YFGoD0FmI9RCLgybo="
	on:
		tags: true
		all_branches: true
		rvm: 2.0.0
		condition: "$FUTURE_PARSER = yes"
